#!/bin/bash
# TCG Power Dialer — Environment Setup
# This script creates the .env file with credentials for the dialer dashboard and GHL CRM.
# Run this on first use or when credentials need to be updated.

set -e

ENV_FILE=".env"

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
  echo "Found existing .env file."
  echo "Current contents:"
  echo "---"
  cat "$ENV_FILE"
  echo "---"
  read -p "Overwrite? (y/N): " OVERWRITE
  if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
    echo "Keeping existing .env. Done."
    exit 0
  fi
fi

echo ""
echo "=== TCG Power Dialer Setup ==="
echo ""

# Dashboard URL
read -p "Dashboard URL (e.g. https://your-app.vercel.app): " DASHBOARD_URL
if [ -z "$DASHBOARD_URL" ]; then
  echo "Error: Dashboard URL is required."
  exit 1
fi

# Dialer API Key
read -p "Dialer API Key: " DIALER_API_KEY
if [ -z "$DIALER_API_KEY" ]; then
  echo "Error: Dialer API Key is required."
  exit 1
fi

# GHL API Key
read -p "GHL API Key (PIT token): " GHL_API_KEY
if [ -z "$GHL_API_KEY" ]; then
  echo "Error: GHL API Key is required."
  exit 1
fi

# GHL Location ID (default to TCG's)
read -p "GHL Location ID [n778xwOps9t8Q34eRPfM]: " GHL_LOCATION_ID
GHL_LOCATION_ID="${GHL_LOCATION_ID:-n778xwOps9t8Q34eRPfM}"

# Write .env
cat > "$ENV_FILE" << EOF
# TCG Power Dialer — Credentials
# Generated by setup-env.sh on $(date)

# Dashboard (where the dialer app is deployed)
DASHBOARD_URL=$DASHBOARD_URL
DIALER_API_KEY=$DIALER_API_KEY

# GoHighLevel CRM (for direct contact/deal lookups)
GHL_API_KEY=$GHL_API_KEY
GHL_LOCATION_ID=$GHL_LOCATION_ID
EOF

echo ""
echo "Credentials saved to $ENV_FILE"
echo "You're good to go — tell Claude to start dialing."
